### ISSUE TITLE
Depreaction

### ISSUE THREAD

**Issue by Vilican** [ckeditor-for-wordpress/ckeditor-for-wordpress#18]
I noticed this error when in debug mode:

Notice: Function wp_richedit_pre is deprecated from 4.3! Use the function format_for_editor(). in ***/wp-includes/functions.php on line 3406

Note: **\* replace absolute path on the server

**Comment by wwalc** [comment]
Thanks for the report! Any chance for a PR? :)

**Comment by Vilican** [comment]
What do you mean by PR?

**Comment by wwalc** [comment]
Ah, sorry for not being clear. PR = Pull request the we could merge.

**Comment by Vilican** [comment]
Well, sorry. Although I am a programmer, I have just started with WordPress.
