### ISSUE TITLE
Title of the HTML tags

### ISSUE THREAD

**Issue by Leiouflying** [ckeditor-for-wordpress/ckeditor-for-wordpress#23]
The plug-in use:
```
<h1>
        Title
</h1>
```
But some themes may cause some trouble such as some function may get one more space. It may cause the article very messy. 
I think you can try to change the code to:
`<h1>Title</h1>`

The official editor of WordPress use it too.

**Comment by wwalc** [comment]
To get rid of whitespaces you can try changing the CKEditor configuration to something like

	var dtd = CKEDITOR.dtd;
	for ( var e in CKEDITOR.tools.extend( {}, dtd.$nonBodyContent, dtd.$block, dtd.$listItem, dtd.$tableContent ) ) {
		this.dataProcessor.writer.setRules( e, {
			indent: false,
			breakBeforeOpen: false,
			breakAfterOpen: false,
			breakBeforeClose: false,
			breakAfterClose: false
		});
	}

See https://sdk.ckeditor.com/samples/htmlformatting.html and https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_output_format
