### ISSUE TITLE
Useful Links section is outdated

### ISSUE THREAD

**Issue by vokiel** [ckeditor-for-wordpress/ckeditor-for-wordpress#5]
* Plugin Site: http://wordpress.org/extend/plugins/ckeditor-for-wordpress/
 * should be: https://wordpress.org/plugins/ckeditor-for-wordpress/
* 3.x version
 * User Guide: http://docs.cksource.com/CKEditor_3.x/Users_Guide
 * CKEditor Documentation: http://docs.cksource.com/CKEditor_3.x/Developers_Guide
 * Configuration Options: http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html

**Comment by wwalc** [comment]
Fixed in ba96657951547d0edd127bcc5937a63d79027b85.
